// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TofEA.Model;

#nullable disable

namespace ToFEA.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240216230226_Migr4")]
    partial class Migr4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("ToFEA.Model.BaseStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value3")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SlotId");

                    b.HasIndex("StatId");

                    b.ToTable("BaseStats");
                });

            modelBuilder.Entity("ToFEA.Model.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfStars")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ToFEA.Model.PossibleStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("InitValue")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MaxUpgradeValue")
                        .HasColumnType("REAL");

                    b.Property<float>("MinUpgradeValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("PossibleStats");
                });

            modelBuilder.Entity("ToFEA.Model.PossibleTitanStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("PossibleTitanStats");
                });

            modelBuilder.Entity("ToFEA.Model.TitanStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTitanStatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitanLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTitanStatId");

                    b.HasIndex("SlotId");

                    b.ToTable("TitanStats");
                });

            modelBuilder.Entity("TofEA.Model.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("ToFEA.Model.BaseStat", b =>
                {
                    b.HasOne("ToFEA.Model.Equipment", null)
                        .WithMany("BaseStat")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("TofEA.Model.EquipmentType", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToFEA.Model.PossibleStat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("ToFEA.Model.Equipment", b =>
                {
                    b.HasOne("TofEA.Model.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("ToFEA.Model.PossibleStat", b =>
                {
                    b.HasOne("TofEA.Model.EquipmentType", null)
                        .WithMany("PossibleStat")
                        .HasForeignKey("EquipmentTypeId");
                });

            modelBuilder.Entity("ToFEA.Model.PossibleTitanStat", b =>
                {
                    b.HasOne("TofEA.Model.EquipmentType", null)
                        .WithMany("PossibleTitanStat")
                        .HasForeignKey("EquipmentTypeId");
                });

            modelBuilder.Entity("ToFEA.Model.TitanStat", b =>
                {
                    b.HasOne("ToFEA.Model.PossibleTitanStat", "CurrentTitanStat")
                        .WithMany()
                        .HasForeignKey("CurrentTitanStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToFEA.Model.Equipment", "Slot")
                        .WithMany("TitanStat")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTitanStat");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("ToFEA.Model.Equipment", b =>
                {
                    b.Navigation("BaseStat");

                    b.Navigation("TitanStat");
                });

            modelBuilder.Entity("TofEA.Model.EquipmentType", b =>
                {
                    b.Navigation("PossibleStat");

                    b.Navigation("PossibleTitanStat");
                });
#pragma warning restore 612, 618
        }
    }
}
